SERVER_PORT = 8080

POSTGRES_HOST = localhost
POSTGRES_PORT = 5432
POSTGRES_DB = reactive_product_catalog_service
POSTGRES_USERNAME = postgres
POSTGRES_PASSWORD = postgres

REACTIVE_RATING_SERVICE_URL = http://localhost:8081
REACTIVE_RATING_SERVICE_TIMEOUT = 60000
REACTIVE_RATING_SERVICE_RETRIES_NUMBER = 2